Repository vanessa-opensource/add, pull requests merged in 2018-05, with the labels that each got.

#135 Исправление падения при выполнении параллельных шагов - перенос инициализации до тестирования
  Jenkinsfile
Labels: tech.debt

#137 Методика работы с объемными исходниками
  doc/erp-sources.md
Labels: docs

#146 УФ: Исправлена проблема загрузки файлов тестов xUnit, когда есть расхождение между именем файла и именем обработки
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Ext/ObjectModule.bsl
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Forms/Форма/Ext/Form/Module.bsl
Labels: tdd, tech.debt

#153 Сокращение длинного имени файла https://github.com/silverbulleters/ad…
  features/libraries/TestClients/step_definitions/many_test_clients_one_scenario/many_test_clients_one_scenario.xml
  features/libraries/TestClients/step_definitions/many_test_clients_one_scenario/many_test_clients_one_scenario/Ext/ObjectModule.bsl
  features/libraries/TestClients/step_definitions/many_test_clients_one_scenario/many_test_clients_one_scenario/Forms/Форма.xml
  features/libraries/TestClients/step_definitions/many_test_clients_one_scenario/many_test_clients_one_scenario/Forms/Форма/Ext/Form.xml
  features/libraries/TestClients/step_definitions/many_test_clients_one_scenario/many_test_clients_one_scenario/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior
