Repository vanessa-opensource/add, pull requests merged in 2018-08, with the labels that each got.

#260 Feature/jsonserialization
  .travis.yml
  Jenkinsfile
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form.xml
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Forms/Форма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеПростогоСправочникаJSON.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеПростогоСправочникаJSON/Ext/Template.txt
Labels: Генерация данных

#267 Feature/issue 258
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Forms/Форма.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Forms/Форма/Ext/Form.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Templates/ДокументСДвижениямиПоРегистрамНакопления.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Templates/ДокументСДвижениямиПоРегистрамНакопления/Ext/Template.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Templates/ДокументСДвижениямиПоРегистрамСведений.xml
  features/libraries/Макеты/step_definitions/СозданиеДокументовСДвижениями/СозданиеДокументовСДвижениями/Templates/ДокументСДвижениямиПоРегистрамСведений/Ext/Template.xml
  features/libraries/Макеты/СозданиеДокументовСДвижениями.feature
  lib/CF/83NoSync/AccumulationRegister.РегистрНакопленияОбороты.xml
  lib/CF/83NoSync/AccumulationRegister.РегистрНакопленияОстатки.xml
  lib/CF/83NoSync/Configuration.xml
  lib/CF/83NoSync/Document.ДокументСДвижениями.ObjectModule.txt
  lib/CF/83NoSync/Document.ДокументСДвижениями.xml
  lib/CF/83NoSync/InformationRegister.РСПодчиненРегистраторуПериодический.xml
  lib/CF/83NoSync/Subsystem.Основная.xml
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
Labels: good first issue, Генерация данных

#279 Новый шаг я загружаю макет "Макет" с переменными
  features/libraries/Макеты/step_definitions/СозданиеFixturesПоМакетуОбработкиФичи/СозданиеFixturesПоМакетуОбработкиФичи/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/СозданиеFixturesПоМакетуОбработкиФичи.feature
Labels: behavior, Генерация данных

#283 Пропуск форм, при открытии которых выдан определенный текст исключения, при дымовом тестировании
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/Настройки/Настройки/Forms/Форма/Ext/Form/Module.bsl
  plugins/Файлы/Файлы/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/readme.md
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации.xml
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tools/JSON/xUnitParams.json
Labels: smoke, tdd, tech.debt

#293 Исправлена ошибка удаления существующих объектов при запуске дымовых…
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: smoke

#303 Доработана загрузка тестов из истории для случае асинхронного режима
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd, tech.debt
