Repository vanessa-opensource/add, pull requests merged in 2018-07, with the labels that each got.

#227 Добавлены исходники внешних инструментов из tools/epf/utils
  tools/epf/utils/xddGuidShow/xddGuidShow/Forms/Форма/Ext/Form.bin
  tools/epf/utils/xddGuidShow/xddGuidShow/Forms/Форма/Ext/Form/Module.bsl
  tools/epf/utils/xddGuidShow/xddGuidShow/Forms/Форма/Ext/Form/form
  tools/epf/utils/xddTestsConvertIntoRebornFormat/xddTestsConvertIntoRebornFormat/Forms/Форма/Ext/Form.bin
  tools/epf/utils/xddTestsConvertIntoRebornFormat/xddTestsConvertIntoRebornFormat/Forms/Форма/Ext/Form/Module.bsl
  tools/epf/utils/xddTestsConvertIntoRebornFormat/xddTestsConvertIntoRebornFormat/Forms/Форма/Ext/Form/form
Labels: 1script, tech.debt

#228 Feature/tools folder inside build 198
  ospx/settings.json
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации.xml
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: 1script, smoke

#229 Доработка поиска активного окна, доработка указания при выборе из спи…
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#237 Инструмент для управления настройками дымовых тестов
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tools/epf/utils/СозданиеФайлаНастроекДляДымовыхТестов/СозданиеФайлаНастроекДляДымовыхТестов.xml
  tools/epf/utils/СозданиеФайлаНастроекДляДымовыхТестов/СозданиеФайлаНастроекДляДымовыхТестов/Forms/Форма.xml
  tools/epf/utils/СозданиеФайлаНастроекДляДымовыхТестов/СозданиеФайлаНастроекДляДымовыхТестов/Forms/Форма/Ext/Form.xml
  tools/epf/utils/СозданиеФайлаНастроекДляДымовыхТестов/СозданиеФайлаНастроекДляДымовыхТестов/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke

#240 Использовение переменных контекста в сценарии "И я буду выбирать внешний файл "ИмяФайла""
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, good first issue

#232 Исправление сборки travis
  .travis.yml
Labels: tech.debt

#239 При генерации файла обработки приводим имя в нормализованное
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form/Module.bsl
  lib/featurereader/vbFeatureReader/vbFeatureReader/Ext/ObjectModule.bsl
Labels: behavior

#242 Исправил ошибку загрузки макетов в режиме совместимости 8.2 (#212)
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
Labels: tech.debt, Генерация данных

#245 Добавление автопоказа отчета allure #233
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior, good first issue

#251 Выделение шагов работы с БД в отдельный фича-файл
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/step_definitions/ПодключениеНесколькихКлиентовТестированияБиблиотека/ПодключениеНесколькихКлиентовТестированияБиблиотека/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД.xml
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Forms/Форма.xml
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Forms/Форма/Ext/Form.xml
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Templates/Макет.xml
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Templates/Макет/Ext/Template.xml
  features/libraries/Данные/ЗапросыКБД.feature
  features/libraries/Макеты/step_definitions/СуществованиеЭлементов/СуществованиеЭлементов.xml
  features/libraries/Макеты/step_definitions/СуществованиеЭлементов/СуществованиеЭлементов/Ext/ObjectModule.bsl
  features/libraries/Макеты/step_definitions/СуществованиеЭлементов/СуществованиеЭлементов/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/СуществованиеЭлементов.feature
Labels: behavior

#259 Исправление ошибок при записи видео. В файле параметров VBParams836UF…
  lib/video/РаботаСВидео/РаботаСВидео/Forms/Форма/Ext/Form/Module.bsl
  tools/JSON/VBParams836UF.json
Labels: behavior

#236 Для дымовых тестов открытия форм конфигурации добавлена проверка на наличии имени формы в списке исключений.
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: question, smoke
