Repository vanessa-opensource/add, pull requests merged in 2018-11, with the labels that each got.

#354 Определение типа маршрута бизнес процесса.
  lib/CF/83xdd/Catalogs/ПростойСправочник3.xml
  lib/CF/83xdd/Configuration.xml
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеСправочника3_с_РеквизитомСоставногоТипаТочкиМаршрута.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеСправочника3_с_РеквизитомСоставногоТипаТочкиМаршрута/Ext/Template.xml
Labels: Генерация данных

#357 Совместимость инструментов с 8.3.5 / 8.2 + ОФ: Вывод дымовых тестов в ЖР по умолчанию
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tools/epf/utils/УправлениеДымовымиТестами/УправлениеДымовымиТестами/Forms/Форма/Ext/Form/Module.bsl
Labels: 8.2, tech.debt

#359 ОФ: Исправлена ошибка с дублированием СтрШаблон_ в области видимости
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form.bin
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form/form
Labels: 8.2, tdd, tech.debt

#352 Чтение глобальных переменных в тест клиенте
  features/libraries/TestClients/step_definitions/РаботаСTestClient/РаботаСTestClient/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#355 Новый параметр запуска для sikulix
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
  plugins/ЗагрузчикПользовательскихНастроек/ЗагрузчикПользовательскихНастроек/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#361 Feature/issue 360
  plugins/ИтераторМетаданных/ИтераторМетаданных.xml
  plugins/ИтераторМетаданных/ИтераторМетаданных/Ext/ObjectModule.bsl
  plugins/ИтераторМетаданных/ИтераторМетаданных/Forms/Форма.xml
  plugins/ИтераторМетаданных/ИтераторМетаданных/Forms/Форма/Ext/Form.xml
  plugins/ИтераторМетаданных/ИтераторМетаданных/Forms/Форма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_ИтераторМетаданных/Тесты_ИтераторМетаданных.xml
  tests/xunit/Plugins/Тесты_ИтераторМетаданных/Тесты_ИтераторМетаданных/Ext/ObjectModule.bsl
Labels: plugins, smoke, tdd
