Repository vanessa-opensource/add, pull requests merged in 2018-04, with the labels that each got.

#90 Исправление запуска сборки при харенение обработок с исходниками.
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tasks/init.os
  tasks/initib.os
  tasks/Модули/НастройкиОкружения.os
  tools/JSON/VBParams.json
  tools/JSON/env.json.file
  tools/JSON/env.json.file.build
  tools/JSON/env.json.server
  tools/JSON/env.json.server.build
Labels: behavior

#92 Feature/travistests
  .travis.yml
  Jenkinsfile
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШага/Ext/Form/Module.bsl
  features/Core/TestClient/HTML-report.feature
  features/Core/TestClient/Issue_148_Video_Make.feature
  features/Core/TestClient/Issue_149_ДелатьСкриншотПриОшибке.feature
  features/Core/TestClient/Issue_34_ОтчетAllure.feature
  features/Core/TestClient/Markdown_report.feature
  features/Core/TestClient/ПроверкаОстановкиВыполненияОдногоСценария.feature
  features/Core/TestClient/ПроверкаТегаTreeПеревод.feature
  lib/video/работасвидео/РаботаСВидео.xml
  lib/video/работасвидео/РаботаСВидео/Forms/Форма.xml
  lib/video/работасвидео/РаботаСВидео/Forms/Форма/Ext/Form.xml
  lib/video/работасвидео/РаботаСВидео/Forms/Форма/Ext/Form/Module.bsl
  tasks/init.os
  tasks/initib.os
  tasks/vanessatravis.os
  tools/JSON/VBParams8310linux.json
  tools/linux/dockerdownload.sh
  tools/linux/travistest.sh
  tools/runner.os
Labels: behavior

#109 Строгий порядок выполнения любых тестов, в т.ч. и дымовых тестов, а не только сценарных тестов
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ЗагрузчикИзПодсистемКонфигурации/ЗагрузчикИзПодсистемКонфигурации/Ext/ObjectModule.bsl
  plugins/ЗагрузчикИзПодсистемКонфигурации/ЗагрузчикИзПодсистемКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Ext/ObjectModule.bsl
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Forms/Форма/Ext/Form/Module.bsl
  plugins/ПостроительДереваТестов/ПостроительДереваТестов/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tools/JSON/xUnitParams.json
Labels: tdd, tech.debt

#94 Использование Ansible для настройки сборочных нод
  .gitignore
  tools/ansible/README.md
  tools/ansible/Vagrantfile
  tools/ansible/ansible-setup.sh
  tools/ansible/ansible.cfg
  tools/ansible/img/54dbf0.jpg
  tools/ansible/inventories/local/group_vars/all
  tools/ansible/keys/README.md
  tools/ansible/keys/vagrant
  tools/ansible/keys/vagrant.pub
  tools/ansible/logs/.gitkeep
  tools/ansible/playbooks/setup-win-node-add.yml
  tools/ansible/roles/windowsconfig/tasks/main.yml
  tools/jenkins/README.md
Labels: docs, tech.debt

#116 Обход ошибки платформы по созданию ключа записи регистра сведений на клиенте
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: plugins, Генерация данных

#119 Испавление чтения настроек json на платформенное, если возможно.
  epf/bddRunner/bddRunner/Ext/ObjectModule.bsl
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
  tools/JSON/VBParams8310UF.json
  tools/JSON/VBParams8310linux.json
Labels: tech.debt
