Repository vanessa-opensource/add, pull requests merged in 2018-06, with the labels that each got.

#161 Develop
  tools/ansible/README.md
  tools/ansible/inventories/local/group_vars/all
  tools/ansible/inventories/local/group_vars/test1
  tools/ansible/inventories/local/group_vars/test2
  tools/ansible/roles/add/defaults/main.yml
  tools/ansible/roles/add/tasks/choco.yml
  tools/ansible/roles/add/tasks/main.yml
  tools/ansible/roles/add/tasks/vlc.yml
  tools/ansible/roles/allure/tasks/main.yml
  tools/ansible/roles/oscript/tasks/main.yml
Labels: enhancement

#165 Тесты для пользователей
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form.bin
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form/form
  plugins/ВыводВЛогФайл/ВыводВЛогФайл/Ext/ObjectModule.bsl
  plugins/ВыводВЛогФайл/ВыводВЛогФайл/Forms/Форма/Ext/Form/Module.bsl
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Forms/Форма/Ext/Form/Module.bsl
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей.xml
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Ext/ObjectModule.bsl
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Forms/Форма.xml
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Forms/Форма/Ext/Form.xml
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Forms/Форма/Ext/Form/Module.bsl
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Templates/xUnitParams_json.xml
  plugins/ЗапускТестовДляПользователей/ЗапускТестовДляПользователей/Templates/xUnitParams_json/Ext/Template.txt
  plugins/Настройки/Настройки/Ext/ObjectModule.bsl
  plugins/Настройки/Настройки/Forms/Форма/Ext/Form/Module.bsl
  plugins/Пользователи/Пользователи.xml
  plugins/Пользователи/Пользователи/Ext/ObjectModule.bsl
  plugins/Пользователи/Пользователи/Forms/Форма.xml
  plugins/Пользователи/Пользователи/Forms/Форма/Ext/Form.xml
  plugins/Пользователи/Пользователи/Forms/Форма/Ext/Form/Module.bsl
  plugins/Пользователи/Пользователи/Templates/СозданиеОдногоПользователяИБ.xml
  plugins/Пользователи/Пользователи/Templates/СозданиеОдногоПользователяИБ/Ext/Template.xml
  plugins/Пользователи/Пользователи/Templates/СозданиеОдногоПользователяИБ_УФ.xml
  plugins/Пользователи/Пользователи/Templates/СозданиеОдногоПользователяИБ_УФ/Ext/Template.xml
  plugins/Файлы/Файлы.xml
  plugins/Файлы/Файлы/Ext/ObjectModule.bsl
  plugins/Файлы/Файлы/Forms/Форма.xml
  plugins/Файлы/Файлы/Forms/Форма/Ext/Form.xml
  plugins/Файлы/Файлы/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/ПолучениеФорм/Ext/Form.bin
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/ПолучениеФорм/Ext/Form/form
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тест_ЗапускТестовДляПользователей/Тест_ЗапускТестовДляПользователей.xml
  tests/xunit/Plugins/Тест_ЗапускТестовДляПользователей/Тест_ЗапускТестовДляПользователей/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_ГенераторОтчетаJUnitXML_TFS/Тесты_ГенераторОтчетаJUnitXML_TFS.xml
  tests/xunit/Plugins/Тесты_ГенераторОтчетаJUnitXML_TFS/Тесты_ГенераторОтчетаJUnitXML_TFS/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_ГенераторОтчетаJUnitXML_TFS/Тесты_ГенераторОтчетаJUnitXML_TFS/Templates/Эталон_ОтчетОТестировании.xml
  tests/xunit/Plugins/Тесты_ГенераторОтчетаJUnitXML_TFS/Тесты_ГенераторОтчетаJUnitXML_TFS/Templates/Эталон_ОтчетОТестировании/Ext/Template.txt
  tools/JSON/xUnitParams.json
Labels: tdd, tech.debt

#175 Перенос из VB 1.1.131 + исправление различных ошибок
  README.md
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Ext/ObjectModule.bsl
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form.bin
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/Core/ExpectedSomething/ExpectedForms.feature
  features/Core/OpenForm/ОткрытиеФормы.feature
  features/Core/TestClient/step_definitions/Issue_461_Обработка_временной_фичи/Issue_461_Обработка_временной_фичи/Forms/Форма/Ext/Form/Module.bsl
  features/Core/TestClient/step_definitions/Issue_461_Обработка_временной_фичи/Issue_461_Обработка_временной_фичи/Templates/СгенерированныйСценарий/Ext/Template.txt
  features/Core/TestClient/ПроверкаШагаЯКопируюТекущийПрофильTestClient.feature
  features/Support/Templates/ДляПроверкаШагаЯКопируюТекущийПрофильTestClient.feature
  features/Support/Templates/СлужебнаяФичаEN3.feature
  features/libraries/TestClients/step_definitions/РаботаСTestClient/РаботаСTestClient/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/TestClients/Подключение клиента тестирования с параметрами.feature
  features/libraries/UITestRunner/step_definitions/ПроверкаЗначенияМакета/ПроверкаЗначенияМакета/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсомДополнительный/РаботаСИнтерфейсомДополнительный/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/step_definitions/СозданиеFixturesПоМакетуОбработкиФичи/СозданиеFixturesПоМакетуОбработкиФичи/Ext/ObjectModule.bsl
  features/libraries/Макеты/step_definitions/СозданиеFixturesПоМакетуОбработкиФичи/СозданиеFixturesПоМакетуОбработкиФичи/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/СозданиеFixturesПоМакетуОбработкиФичи.feature
  features/libraries/ПакетныйРежим/ПакетныйРежим/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Пауза/step_definitions/СделатьПаузу/СделатьПаузу/Forms/Форма/Ext/Form.xml
  features/libraries/Пауза/step_definitions/СделатьПаузу/СделатьПаузу/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Условие/step_definitions/Условие/Условие/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Цикл/step_definitions/Цикл/Цикл/Forms/Форма/Ext/Form/Module.bsl
  lib/featurereader/vbFeatureReader/vbFeatureReader/Ext/ObjectModule.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
  spec/fixtures/ЗагрузкаОдногоЭлементаСправочника1.mxl
  tools/JSON/VBParams8310UF.json
  tools/JSON/vrunner.json
  tools/localbuild.cmd
Labels: behavior, tech.debt
