Repository vanessa-opensource/add, pull requests merged in 2019-02, with the labels that each got.

#399 Сохранение отчета Allure после выполнения сценария
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/Аллюр2Отчет/Аллюр2Отчет/Ext/ObjectModule.bsl
Labels: behavior

#370 Корректное сравнение заголовков форм
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#381 Добавление плагина Заглушки
  doc/xdd/Заглушки.MD
  plugins/Данные/Данные.xml
  plugins/Данные/Данные/Ext/ObjectModule.bsl
  plugins/Данные/Данные/Forms/Форма.xml
  plugins/Данные/Данные/Forms/Форма/Ext/Form.xml
  plugins/Данные/Данные/Forms/Форма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные.xml
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Forms/Форма.xml
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Forms/Форма/Ext/Form.xml
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Forms/Форма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Templates/МакетДанные.xml
  tests/xunit/Plugins/Тесты_Данные/Тесты_Данные/Templates/МакетДанные/Ext/Template.xml
  tools/TextTemplate_Unit.st
Labels: Генерация данных

#403 Дымовые тесты открытия форм через тест-клиент - решение проблемы с модальными окнами
  README.md
  doc/README.md
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/readme.md
  tests/smoke/smoke.example.json
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации.xml
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tools/JSON/xUnitParams.json
Labels: Enterprise support, smoke

#404 Добавить шаг "Когда я отвечаю на это сообщение"
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Плагины/Фича_ИнтернетПочта.feature
Labels: behavior, plugins

#406 Шаг "И Я закрыл все окна клиентского приложения кроме "Нужное окно"" не всегда закрывает все окна
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#407 Feature/smoke input based on config
  tests/smoke/Smoke_InputBasedOn/Smoke_InputBasedOn.xml
  tests/smoke/Smoke_InputBasedOn/Smoke_InputBasedOn/Ext/ObjectModule.bsl
  tests/smoke/Smoke_InputBasedOn/Smoke_InputBasedOn/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/readme.md
  tests/smoke/smoke.example.json
Labels: Enterprise support, smoke

#400 Загрузка глобальных переменных из Consul-а
  doc/xdd/Загрузчик-пользовательских-настроек.MD
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
  plugins/ЗагрузчикПользовательскихНастроек/ЗагрузчикПользовательскихНастроек/Forms/Форма/Ext/Form.xml
  plugins/ЗагрузчикПользовательскихНастроек/ЗагрузчикПользовательскихНастроек/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#413 Исправить алгоритм определения поддержки асинхронных вызовов
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd, tech.debt

#416 Исправить отчеты в пакетном+синхронном режиме (#414)
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd

#412 Добавление бизнес-процессов в дымовые тесты
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс1.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс1/Forms/ФормаБизнесПроцесса.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс1/Forms/ФормаБизнесПроцесса/Ext/Form.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс1/Forms/ФормаСписка.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс1/Forms/ФормаСписка/Ext/Form.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс2.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс2/Forms/ФормаБизнесПроцесса.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс2/Forms/ФормаБизнесПроцесса/Ext/Form.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс2/Forms/ФормаСписка.xml
  lib/CF/83xdd/BusinessProcesses/БизнесПроцесс2/Forms/ФормаСписка/Ext/Form.xml
  tests/smoke/readme.md
  tests/smoke/smoke.example.json
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: smoke, tech.debt

#421 fix(РаботаСТестКлиентом) Исправлена функция подставляющая глобальные …
  features/libraries/TestClients/step_definitions/РаботаСTestClient/РаботаСTestClient/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior
