Repository vanessa-opensource/add, pull requests merged in 2019-11, with the labels that each got.

#605 Исправлено ошибочное внесенное контрибьютором изменение, сломавшее сохранение/восстановление параметров-списков - КаталогиБиблиотек, Теги и т.п.
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior, bug

#608 Добавил шаги для проверки модифицированности формы
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсомДополнительный/РаботаСИнтерфейсомДополнительный/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/РаботаСИнтерфейсомДополнительный.feature
Labels: behavior

#619 fix: Исправление ошибок библиотеки Файловые операции
  features/libraries/Файлы/step_definitions/Файловые_операции/Файловые_операции/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, bug

#613 Группировка faq по разделам
  F.A.Q.MD
Labels: docs

#620 При передаче 0 в метод шага передается "0"
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior, bug
