Repository vanessa-opensource/add, pull requests merged in 2019-12, with the labels that each got.

#623 Faqeditbranch
  F.A.Q.MD
Labels: docs

#627 Исправить ошибку при запуске из 64-разрядного клиента
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins, smoke

#628 Сравнивать таблицы с многострочными заголовками
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior
