Repository vanessa-opensource/add, pull requests merged in 2019-09, with the labels that each got.

#539 Добавить json-настройку для теста Тесты_КомандныйИнтерфейс
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс.xml
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke, tech.debt

#542 Исправить выдачу числовых полей при заполнении сценария в BDD 63
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior, bug

#547 Проверка признака Client (ordinary application) в тесте Tests_SmokeCommonModules
  tests/smoke/Tests_SmokeCommonModules/Tests_SmokeCommonModules.xml
  tests/smoke/Tests_SmokeCommonModules/Tests_SmokeCommonModules/Ext/ObjectModule.bsl
Labels: smoke

#550 Подготовка релиза 6.2.0
  doc/history.MD
  epf/bddRunner/bddRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  lib/CF/83/Configuration.xml
  lib/CF/83NoSync/Configuration.xml
  lib/CF/83xdd/Configuration.xml
  lib/CF/83xddNoSync/Configuration.xml
  packagedef
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
Labels: docs

#563 Update F.A.Q.MD
  F.A.Q.MD
Labels: behavior, docs

#554 Добавил проверку ОМ ПолныеПрава, closes #553
  tests/smoke/Tests_SmokeCommonModules/Tests_SmokeCommonModules/Ext/ObjectModule.bsl
Labels: smoke

#566 Исправлена ошибка формирования скриншота
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior
