Repository vanessa-opensource/add, pull requests merged in 2019-08, with the labels that each got.

#521 Исправил ошибку дымового теста открытия форм, при определенных настро…
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
Labels: smoke

#519 Добавить фильтр сообщений по тексту вложения
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, plugins

#522 Исправил - Нельзя сохранить макет в файл в асинхронном режиме
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: Генерация данных

#524 Исправлена ошибка при отключении теста открытия формы справочников в файле настроек и добавлено удаление создаваемого элемента-владельца
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: smoke

#528 исправлен тест ТестыПроверитьРавенствоТаблиц.ТестДолжен_ПроверитьНеРавенствоТаблиц_НечеткоеСравнение
  tests/xunit/Plugins/ТестыПроверитьРавенствоТаблиц/ТестыПроверитьРавенствоТаблиц/Ext/ObjectModule.bsl
Labels: tdd

#529 Исправлены шаги проверки существования файлов/каталогов по шаблону с "*" или "?"
  features/libraries/Файлы/step_definitions/Файловые_операции/Файловые_операции/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, bug

#527 Исправлено разное количество тестов в junit-отчете и отчете Аллюр
  doc/PluginsTemplates/ШаблонГенератораОтчета/ШаблонГенератораОтчета/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ГенераторОтчетаJUnitXML/ГенераторОтчетаJUnitXML/Ext/ObjectModule.bsl
  plugins/ГенераторОтчетаJUnitXML/ГенераторОтчетаJUnitXML/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins, tdd

#530 Исправил ошибочные имена сценариев
  features/libraries/Условие/УсловиеИначе.feature
Labels: behavior, bug

#513 Обобщить методы для работы с клиентами тестирования
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form.xml
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, plugins, tdd

#531 удалены ненужные присваивания
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШага/Ext/Form/Module.bsl
Labels: behavior, tdd

#533 Чтение переменных окружения
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/libraries/ПеременныеОкружения/step_definitions/ПеременныеОкружения/Переменные_окружения.xml
  features/libraries/ПеременныеОкружения/step_definitions/ПеременныеОкружения/Переменные_окружения/Forms/Форма.xml
  features/libraries/ПеременныеОкружения/step_definitions/ПеременныеОкружения/Переменные_окружения/Forms/Форма/Ext/Form.xml
  features/libraries/ПеременныеОкружения/step_definitions/ПеременныеОкружения/Переменные_окружения/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/ПеременныеОкружения/Переменные окружения.feature
  features/libraries/Плагины/step_definitions/Фича_РегулярныеВыражения/Фича_РегулярныеВыражения/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior
