Repository vanessa-opensource/add, pull requests merged in 2019-01, with the labels that each got.

#386 Ошибка при инициализации настроек на сервере
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
Labels: bug, tdd

#393 Потоковый вывод результатов тестов
  doc/PluginsTemplates/ШаблонГенератораОтчета/ШаблонГенератораОтчета/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ГенераторОтчетаAllureXMLВерсия2/ГенераторОтчетаAllureXMLВерсия2/Ext/ObjectModule.bsl
  plugins/ГенераторОтчетаAllureXMLВерсия2/ГенераторОтчетаAllureXMLВерсия2/Forms/Форма/Ext/Form/Module.bsl
  plugins/ГенераторОтчетаJUnitXML/ГенераторОтчетаJUnitXML/Ext/ObjectModule.bsl
  plugins/ГенераторОтчетаJUnitXML/ГенераторОтчетаJUnitXML/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke, tdd

#396 Issue 340
  features/libraries/Smoke/Smoke_InputBasedOn/Smoke_InputBasedOn/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/Smoke_InputBasedOn/Smoke_InputBasedOn/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke, tdd

#394 Плагин ИнтернетПочта
  features/libraries/Плагины/step_definitions/README.md
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта.xml
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма.xml
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма/Ext/Form.xml
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Плагины/Фича_ИнтернетПочта.feature
Labels: plugins

#398 Исправлена зависимость от БСП #397
  features/libraries/Плагины/step_definitions/Фича_ИнтернетПочта/Фича_ИнтернетПочта/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins
