Repository vanessa-opensource/add, pull requests merged in 2019-04, with the labels that each got.

#451 Исправил путь к OneScript
  .travis.yml
Labels: 1script

#437 Подправил нумерацию
  F.A.Q.MD
  СODE_OF_CONDUCT.md
Labels: docs

#453 исправлены грамматические ошибки в документации
  tests/smoke/readme.md
Labels: docs

#461 Исправление ошибки с запуском дымовых тестов на УПП
  plugins/СтроковыеУтилиты/СтроковыеУтилиты/Ext/ObjectModule.bsl
Labels: plugins

#457 Закрытие при наличии модальных окон
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke, tdd

#436 Небольшой рефакторинг и fix проверки существования каталога
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#459 Общие реквизиты и предопределенные элементы
  plugins/СериализаторMXL/СериализаторMXL.xml
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form.xml
  plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form.bin
  plugins/СериализаторMXL/СериализаторMXL/Forms/Форма/Ext/Form/form
Labels: Генерация данных

#464 Специальный шаг - Я запоминаю каталог проекта в переменную "КаталогПроекта"
  features/libraries/Плагины/step_definitions/Доступ_к_каталогу_проекта/Доступ_к_каталогу_проекта.xml
  features/libraries/Плагины/step_definitions/Доступ_к_каталогу_проекта/Доступ_к_каталогу_проекта/Forms/Форма.xml
  features/libraries/Плагины/step_definitions/Доступ_к_каталогу_проекта/Доступ_к_каталогу_проекта/Forms/Форма/Ext/Form.xml
  features/libraries/Плагины/step_definitions/Доступ_к_каталогу_проекта/Доступ_к_каталогу_проекта/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Плагины/Доступ к каталогу проекта.feature
Labels: behavior

#470 Добавил возможность открытия основной формы ПВХ, issue 467
  .github/CONTRIBUTING.md
  features/libraries/Формы/ОткрытьФормуЧерезКоманду/ОткрытьФормуЧерезКоманду/Forms/Форма/Ext/Form/Module.bsl
  tasks/init.os
  tasks/Модули/Исходники.os
Labels: behavior, docs

#466 Исправление ошибок
  doc/xdd/Загрузчик-пользовательских-настроек.MD
  doc/xdd/Создание-файлов-тестов.MD
  epf/bddRunner/bddRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Forms/Форма/Ext/Form/Module.bsl
  plugins/УтвержденияBDD/УтвержденияBDD/Ext/ObjectModule.bsl
  plugins/УтвержденияПроверкаТаблиц/УтвержденияПроверкаТаблиц/Ext/ObjectModule.bsl
Labels: tdd
