Repository vanessa-opensource/add, pull requests merged in 2020-03, with the labels that each got.

#690 Хелпер для уменьшения ошибок тестирования при выборе текущей строки таблицы, ее разворачивании или сворачивании
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior

#691 ОФ: Помощник известных шагов для обычного приложения
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШагаОФ.xml
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШагаОФ/Ext/Form.bin
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШагаОФ/Ext/Form/Module.bsl
  epf/bddRunner/bddRunner/Forms/ВыборИзвестногоШагаОФ/Ext/Form/form
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form.bin
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form/Module.bsl
  epf/bddRunner/bddRunner/Forms/Форма/Ext/Form/form
  lib/featurereader/vbFeatureReader/vbFeatureReader/Ext/ObjectModule.bsl
Labels: Enterprise support, behavior, tech.debt, ОФ

#693 В генераторе шагов кнопконажималки добавить установку апострофов, если в строке есть начальные или конечные пробелы
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/Core/TestClient/ПолучитьСодержаниеТаблицы.feature
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior

#694 Шаги для управления элементами справочника
  features/libraries/Данные/step_definitions/ЗапросыКБД/ЗапросыКБД/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, good first issue, tech.debt

#698 Поддержка режима совместимости 8.2.16
  README.md
  doc/README.md
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Ext/ObjectModule.bsl
Labels: 8.2, Enterprise support, behavior

#700 Фича и шаги работы с регламентными\фоновыми заданиями
  features/libraries/Данные/step_definitions/Регламентные_задания/Регламентные_задания.xml
  features/libraries/Данные/step_definitions/Регламентные_задания/Регламентные_задания/Forms/Форма.xml
  features/libraries/Данные/step_definitions/Регламентные_задания/Регламентные_задания/Forms/Форма/Ext/Form.xml
  features/libraries/Данные/step_definitions/Регламентные_задания/Регламентные_задания/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Данные/Регламентные задания.feature
  lib/CF/83NoSync/CommonModule.СлужебныйМодуль.Module.txt
  lib/CF/83NoSync/Configuration.xml
  lib/CF/83NoSync/ScheduledJob.РегламентноеЗадание1.xml
Labels: Enterprise support, behavior

#703 Передача параметров внутрь многострочного текста внутри экспортных сценариев
  features/Core/FeatureReader/МногострочныйТекст.feature
  features/Core/FeatureReader/ФичаДляПроверкиМногострочныхСтрокВЭкспортныхСценариях.feature
  lib/featurereader/vbFeatureReader/vbFeatureReader/Ext/ObjectModule.bsl
Labels: Enterprise support, behavior

#677 Feature/duplicatescenario
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#702 issues 701 Использование макетов обработок при разработке на EDT
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/Core/FeatureReader/ПроверкаРаботыСEDT.feature
  features/Support/Templates/edt_project/.project
  features/Support/Templates/edt_project/.settings/org.eclipse.core.resources.prefs
  features/Support/Templates/edt_project/DT-INF/PROJECT.PMF
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT.xml
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Ext/ObjectModule.bsl
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Forms/Форма.xml
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Forms/Форма/Ext/Form.xml
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Forms/Форма/Ext/Form/Module.bsl
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Templates/Тест.xml
  features/Support/Templates/edt_project/bin/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT/Templates/Тест/Ext/Template.xml
  features/Support/Templates/edt_project/src/ExternalDataProcessors/ПоддержкаПроектаВнешнихОбработокEDT/Forms/Форма/Form.form
  features/Support/Templates/edt_project/src/ExternalDataProcessors/ПоддержкаПроектаВнешнихОбработокEDT/Forms/Форма/Module.bsl
  features/Support/Templates/edt_project/src/ExternalDataProcessors/ПоддержкаПроектаВнешнихОбработокEDT/Templates/Тест/Template.mxlx
  features/Support/Templates/edt_project/src/ExternalDataProcessors/ПоддержкаПроектаВнешнихОбработокEDT/ПоддержкаПроектаВнешнихОбработокEDT.mdo
  features/Support/Templates/ПоддержкаПроектаВнешнихОбработокEDT.feature
  features/libraries/VB/step_definitions/ЗапускПростогоСценарияTestClient/ЗапускПростогоСценарияTestClient/Forms/Форма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
  tools/JSON/VBParams8310UF.json
  tools/JSON/VBParams8310UF_FastCheck.json
Labels: behavior

#704 исправлено поведение шага - Тогда Открылось окно предупреждения с заголовком "1С:Предприятие" и текстом "Текст предупреждение!"
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсомДополнительный/РаботаСИнтерфейсомДополнительный/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, bug

#705 Поддержка ключевого слова Функциональность + отчеты Аллюр и Junit формируются с правильными именами функциональностей
  features/libraries/Цикл/ПереборМассива.feature
  lib/featurereader/vbFeatureReader/vbFeatureReader/Ext/ObjectModule.bsl
Labels: behavior

#696 Доработка и оптимизация теста "Командный интерфейс"
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
  tools/JSON/xUnitParams.json
Labels: smoke

#706 Feature/cmd gui fix 695 696
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke

#712 Плагин Информатор для сбора и показа технической информации + шаги Информатора + значительно улучшена работу с шаблонным заменителем * (звездочкой)
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/Support/Templates/ИнформаторСлужебнаяФича.feature
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/step_definitions/РаботаСОкномСообщений/РаботаСОкномСообщений/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Данные/step_definitions/ИнформаторШаги/ИнформаторШаги.xml
  features/libraries/Данные/step_definitions/ИнформаторШаги/ИнформаторШаги/Ext/ObjectModule.bsl
  features/libraries/Данные/step_definitions/ИнформаторШаги/ИнформаторШаги/Forms/Форма.xml
  features/libraries/Данные/step_definitions/ИнформаторШаги/ИнформаторШаги/Forms/Форма/Ext/Form.xml
  features/libraries/Данные/step_definitions/ИнформаторШаги/ИнформаторШаги/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Данные/Информатор.feature
  features/libraries/Плагины/Фича_РегулярныеВыражения.feature
  plugins/Информатор/Информатор.xml
  plugins/Информатор/Информатор/Ext/ObjectModule.bsl
  plugins/Информатор/Информатор/Forms/Форма.xml
  plugins/Информатор/Информатор/Forms/Форма/Ext/Form.xml
  plugins/Информатор/Информатор/Forms/Форма/Ext/Form/Module.bsl
  plugins/РегулярныеВыражения/РегулярныеВыражения/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, plugins, tdd

#709 Закрытие окна авторизации тест клиента
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#711 Проверка вложенных схем СКД
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  lib/CF/83xdd/CommonTemplates/ВложеннаяСхема.xml
  lib/CF/83xdd/CommonTemplates/ВложеннаяСхема/Ext/Template.xml
  lib/CF/83xdd/Configuration.xml
  lib/CF/83xdd/Reports/ВложенныеСхемыСКД.xml
  lib/CF/83xdd/Reports/ВложенныеСхемыСКД/Templates/ОсновнаяСхемаКомпоновкиДанных.xml
  lib/CF/83xdd/Reports/ВложенныеСхемыСКД/Templates/ОсновнаяСхемаКомпоновкиДанных/Ext/Template.xml
  lib/CF/83xddNoSync/CommonTemplates/ВложеннаяСхема.xml
  lib/CF/83xddNoSync/CommonTemplates/ВложеннаяСхема/Ext/Template.xml
  lib/CF/83xddNoSync/Configuration.xml
  lib/CF/83xddNoSync/Reports/ВложенныеСхемыСКД.xml
  lib/CF/83xddNoSync/Reports/ВложенныеСхемыСКД/Templates/ОсновнаяСхемаКомпоновкиДанных.xml
  lib/CF/83xddNoSync/Reports/ВложенныеСхемыСКД/Templates/ОсновнаяСхемаКомпоновкиДанных/Ext/Template.xml
  tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
Labels: smoke

#713 Простой шаг с параметром для быстрого тестирования самой Ванесса-АДД - `Когда Я выполняю служебную фичу "СлужебнаяФича" в VanessaADD в режиме TestClient`
  features/libraries/VB/ВыполнитьСлужебнуюФичуВVanessaADDВTestClient.feature
  features/libraries/VB/ОткрытьVanessaADDВTestClient.feature
  features/libraries/Данные/Информатор.feature
Labels: behavior, tech.debt

#714 В FAQ добавлен чек-лист создания фичи по самотестированию Ванесса-АДД
  .github/CONTRIBUTING.md
  F.A.Q.MD
Labels: behavior, docs

#707 fix: зацикливание в шаге ВТечениеСекундЯВыполняю
  features/libraries/Цикл/step_definitions/Цикл/Цикл/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, question

#715 тесты "Проверка макетов СКД" refactoring
  tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
Labels: tech.debt

#716 Новые шаги - Когда Я запоминаю в переменную "ПроверяемаяСтрока" строку "обычное или мультистрочное значение" и глобальный шаг
  features/libraries/Плагины/step_definitions/Фича_РегулярныеВыражения/Фича_РегулярныеВыражения/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Плагины/Фича_РегулярныеВыражения.feature
Labels: behavior

#718 Раскраска высокоуровневых шагов в зависимости от статуса вложенных шагов
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior, tech.debt

#719 Исправлен баг в шаге "я загружаю макет" - если макет не найден, то шаг не падает, а выполняется дальше
  features/libraries/Макеты/step_definitions/СозданиеFixturesПоМакетуОбработкиФичи/СозданиеFixturesПоМакетуОбработкиФичи/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/СозданиеFixturesПоМакетуОбработкиФичи.feature
  plugins/СериализаторMXL/СериализаторMXL.xml
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior, bug
