Repository vanessa-opensource/add, pull requests merged in 2020-07, with the labels that each got.

#761 feat: Вывод времени выполнения шага и сценария
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#766 fix: Поправил чтение макета JSON
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/libraries/Макеты/step_definitions/СозданиеFixturesПоМакетуОбработкиФичи/СозданиеFixturesПоМакетуОбработкиФичи/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/Макеты/СозданиеFixturesПоМакетуОбработкиФичи.feature
  spec/fixtures/ЗагрузкаОдногоЭлементаСправочника1.json
Labels: behavior, Генерация данных

#763 feat: Дополнительное чтение тегов из ПараметрЗапуска
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#768 Дымовые тесты проведения документов и проверки их движений + тесты печатных форм, в т.ч. и внешних
  .gitignore
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  lib/CF/83xddNoSync/Documents/ДокументСДвижениями.xml
  licenses/LICENSE.tests_for_xUnitFor1C
  plugins/ЗагрузчикФайла/ЗагрузчикФайла/Forms/Форма/Ext/Form/Module.bsl
  plugins/ПостроительДереваТестов/ПостроительДереваТестов/Forms/Форма/Ext/Form/Module.bsl
  plugins/РегулярныеВыражения/РегулярныеВыражения/Ext/ObjectModule.bsl
  tests/smoke/readme.md
  tests/smoke/smoke.bsp.json
  tests/smoke/smoke.example.json
  tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов.xml
  tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
  tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм.xml
  tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
  tools/JSON/xUnitParams.json
Labels: smoke

#769 Настройки для дымовых тестов макетов СКД + настройка включения\отключения для 3х видов дымовых
  doc/history.MD
  tests/smoke/readme.md
  tests/smoke/smoke.bsp.json
  tests/smoke/smoke.example.json
  tests/smoke/тесты_ПроведениеДокументов/тесты_ПроведениеДокументов/Ext/ObjectModule.bsl
  tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД.xml
  tests/smoke/тесты_ПроверкаМакетовСКД/тесты_ПроверкаМакетовСКД/Ext/ObjectModule.bsl
  tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
  tools/JSON/xUnitParams.json
Labels: smoke
