Repository vanessa-opensource/add, pull requests merged in 2020-02, with the labels that each got.

#658 Метод ПолучитьАбсолютныйПутьФайлаИзКаталогаПроекта
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior, tech.debt

#664 Исправление бага с данными аллюр меток
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, bug

#629 feat: Добавлен плагин для проверки орфографии через YaSpeller
  F.A.Q.MD
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ПроверкаОрфографии/ПроверкаОрфографии.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии/Ext/ObjectModule.bsl
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма/Ext/Form.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма/Ext/Form/Module.bsl
  tests/xunit/Plugins/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии.xml
  tests/xunit/Plugins/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Forms/Форма.xml
  tests/xunit/Plugins/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Forms/Форма/Ext/Form.xml
  tests/xunit/Plugins/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Тесты_ПроверкиОрфографии/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins

#669 fix: Исправил положение плагина, а то не собирается проект
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/Ext/ObjectModule.bsl
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма/Ext/Form.xml
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/Forms/Форма/Ext/Form/Module.bsl
  plugins/ПроверкаОрфографии/ПроверкаОрфографии/ПроверкаОрфографии.xml
Labels: bug, plugins

#667 Исправление бага с открытием группы в форме элемента справочника
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: smoke

#668 Возможность создания владельца справочника с видом ПВХ и ПО
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
Labels: smoke, tech.debt

#672 Исправление шага 'И я нажимаю на кнопку с именем "ФормаНастройкаСписка"'
  features/libraries/UITestRunner/ФильтрФормыСпискаЭкспорт.feature
Labels: behavior, bug

#679 Синтаксическая ошибка
  features/libraries/Файлы/step_definitions/Файловые_операции/Файловые_операции/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior, bug

#678 не использовать прямые пути
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior

#682 Исправлено редкое падение загрузки макетов для иерархических планов видов характеристик
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
Labels: Enterprise support, Генерация данных

#685 Исправление запуска тест клиента с доменной авторизацией и ожидание ввода пароля
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins, smoke

#688 Исправление периодически неверной работы асинхронного выполнения в режиме командной строки
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: behavior, tech.debt

#689 Значительное улучшение огромного множества шагов, использующих шаблонную звездочку, + поддержка шаблонов в многстрочных строках
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  features/Core/ExpectedSomething/ExpectedForms.feature
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
  plugins/РегулярныеВыражения/РегулярныеВыражения/Forms/Форма/Ext/Form/Module.bsl
Labels: Enterprise support, behavior, tech.debt
