Repository vanessa-opensource/add, pull requests merged in 2020-01, with the labels that each got.

#642 Дымовой тест режима блокировки выдает ошибку на отчетах, хотя их вообще не нужно анализировать
  tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
Labels: smoke

#638 Исправлена обработка параметра типа Число
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#640 Исправлена загрузка записей регистра накопления из json (#639)
  plugins/СериализаторMXL/СериализаторMXL/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеОднойЗаписиВРегистреНакопленияИзJson.xml
  tests/xunit/Plugins/Тесты_СериализаторMXL/Тесты_СериализаторMXL/Templates/СозданиеОднойЗаписиВРегистреНакопленияИзJson/Ext/Template.txt
Labels: Генерация данных

#631 Fix 593
  plugins/Данные/Данные/Ext/ObjectModule.bsl
Labels: plugins

#643 Дымовой тест "Проверка режима управления блокировкой данных" - исключить ложные срабатывания
  tests/smoke/ПроверкаРежимаБлокировки/ПроверкаРежимаБлокировки/Ext/ObjectModule.bsl
Labels: smoke

#655 Шаги проверки состояния таблиц и макетов умеют правильно работать с многострочными строками
  features/libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/РаботаСИнтерфейсом/Forms/Форма/Ext/Form/Module.bsl
  features/libraries/UITestRunner/РаботаСТаблицами.feature
Labels: Enterprise support, behavior

#651 Feature/issue 650
  doc/xdd/Проверка-таблиц-и-табличных-документов.MD
Labels: docs, tdd
