Repository vanessa-opensource/add, pull requests merged in 2021-11, with the labels that each got.

#927 сделано, что б при поиске занятых портов в линукс выводился пид проце…
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins, smoke, linux

#925 Продолжение #918
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd

#944 чуть уточнил документацию, что б другие не путались как я изначально
  tests/smoke/readme.md
Labels: docs

#938 fix: Исправление метода ПодходящийРежимСовместимостиПлатформы, если у…
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
Labels: tdd

#908 Feature/issue 907
  doc/xdd/Система-плагинов.MD
  doc/xdd/Создание-плагина.MD
Labels: plugins, docs

#956 doc: добавлено описание методов, расширены комментарии
  tests/smoke/Тесты_ШаблонТеста/Тесты_ШаблонТеста/Forms/Форма/Ext/Form/Module.bsl
Labels: tdd, docs

#954 doc: расширено описание методов
  tools/TextTemplate_Unit.st
Labels: tdd, docs

#951 fix:проверка, что РезультатыТестирования заполнено
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd

#959 правка теста Тесты_ПроверкаСоставныхТиповДанных
  tests/smoke/Тесты_ПроверкаСоставныхТиповДанных/Тесты_ПроверкаСоставныхТиповДанных/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke

#931 доработки теста ПроверкаЧтенияНеАдминистраторами
  tests/smoke/readme.md
  tests/smoke/ПроверкаЧтенияНеАдминистраторами/ПроверкаЧтенияНеАдминистраторами/Ext/ObjectModule.bsl
Labels: smoke
