Repository vanessa-opensource/add, pull requests merged in 2021-08, with the labels that each got.

#872 Добавлена документация к плагину "ЗапросыИзБД"
  doc/xdd/ЗапросыИзБД.MD
Labels: plugins, docs

#862 мелкие улучшения читаемости
  doc/README.md
Labels: docs

#877 Использование шаблонов поиска для исключений дымовых тестов
  tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Ext/ObjectModule.bsl
Labels: question, smoke

#886 Для общих модулей с тестами метод API "Инициализация" сделан необязательным
  epf/xddTestRunner/xddTestRunner/Ext/ObjectModule.bsl
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: tdd

#888 [BUG] тесты_ФормированиеПечатныхФорм ошибка при передаче ДополнительныеПараметры
  tests/smoke/тесты_ФормированиеПечатныхФорм/тесты_ФормированиеПечатныхФорм/Ext/ObjectModule.bsl
Labels: smoke
