Repository vanessa-opensource/add, pull requests merged in 2021-02, with the labels that each got.

#834 fix Тесты_ПроверкаИндексированияУстаревшихОбъектовМетаданных
  tests/smoke/Тесты_ПроверкаИндексированияУстаревшихОбъектовМетаданных/Тесты_ПроверкаИндексированияУстаревшихОбъектовМетаданных.xml
  tests/smoke/Тесты_ПроверкаИндексированияУстаревшихОбъектовМетаданных/Тесты_ПроверкаИндексированияУстаревшихОбъектовМетаданных/Forms/Форма/Ext/Form/Module.bsl
  tools/JSON/xUnitParams.json
Labels: smoke

#829 Сделал группы элементов на основной форме сворачиваемыми
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form.xml
  plugins/СериализаторMXL/СериализаторMXL/Forms/УправляемаяФорма/Ext/Form/Module.bsl
Labels: Генерация данных

#835 Плагин УтвержденияBDD - Метод "Метод" принимает параметры Строки\Числа в дополнении к массиву
  plugins/УтвержденияBDD/УтвержденияBDD/Ext/ObjectModule.bsl
  tests/xunit/Plugins/Тесты_УтвержденияBDD/Тесты_УтвержденияBDD/Ext/ObjectModule.bsl
Labels: plugins

#836 Расширение для мок-тестирования - удобно для простой проверки кода, связанного с интеграцией с внешними системами
  lib/cfe/МокТестирование/CommonModules/МокТестирование.xml
  lib/cfe/МокТестирование/CommonModules/МокТестирование/Ext/Module.bsl
  lib/cfe/МокТестирование/Configuration.xml
  lib/cfe/МокТестирование/DataProcessors/МокТестирование.xml
  lib/cfe/МокТестирование/DataProcessors/МокТестирование/Ext/ObjectModule.bsl
  lib/cfe/МокТестирование/Languages/Русский.xml
  lib/cfe/ТестМоков/Catalogs/ПростойСправочник.xml
  lib/cfe/ТестМоков/Catalogs/ПростойСправочник/Ext/ManagerModule.bsl
  lib/cfe/ТестМоков/Catalogs/ПростойСправочник/Ext/ObjectModule.bsl
  lib/cfe/ТестМоков/Configuration.xml
  lib/cfe/ТестМоков/Languages/Русский.xml
Labels: Enterprise support, behavior, tdd

#837 Плагин Данные поддерживает стандартные реквизиты + улучшено получение значения для значений простых типов
  plugins/Данные/Данные/Ext/ObjectModule.bsl
Labels: plugins

#838 Тесты проверки моков
  tests/xunit/mock/тестМоков/тестМоков.xml
  tests/xunit/mock/тестМоков/тестМоков/Ext/ObjectModule.bsl
Labels: behavior, plugins, tdd

#839 Доработка теста КомандныйИнтерфейс
  plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl
  plugins/УтвержденияBDD/УтвержденияBDD/Forms/Форма/Ext/Form/Module.bsl
  tests/smoke/тесты_КомандныйИнтерфейс/тесты_КомандныйИнтерфейс/Forms/Форма/Ext/Form/Module.bsl
Labels: plugins, smoke

#841 добавил параметр ИспользоватьПрямыеПути
  epf/bddRunner/bddRunner.xml
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  plugins/LoadSettings/LoadSettings/Forms/Форма/Ext/Form/Module.bsl
Labels: behavior

#820 XDD Глобально доступный клиентский контекст для модульных тестов
  doc/xdd/Создание-файлов-тестов.MD
  epf/xddTestRunner/xddTestRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  tests/xunit/Core/Тесты_ВыполнениеТестов/Тесты_ВыполнениеТестов/Forms/Форма/Ext/Form/Module.bsl
Labels: tdd

#842 Привел в порядок описание API плагина БазовыеУтверждения
  doc/xdd/Базовые-утверждения.MD
Labels: docs, plugins
