Repository vanessa-opensource/add, pull requests merged in 2021-09, with the labels that each got.

#891 Добавлен генератор отчета в формате Generic Execution
  plugins/ГенераторОтчетаGenericExecution/ГенераторОтчетаGenericExecution.xml
  plugins/ГенераторОтчетаGenericExecution/ГенераторОтчетаGenericExecution/Ext/ObjectModule.bsl
  plugins/ГенераторОтчетаGenericExecution/ГенераторОтчетаGenericExecution/Forms/Форма.xml
  plugins/ГенераторОтчетаGenericExecution/ГенераторОтчетаGenericExecution/Forms/Форма/Ext/Form.xml
  plugins/ГенераторОтчетаGenericExecution/ГенераторОтчетаGenericExecution/Forms/Форма/Ext/Form/Module.bsl
Labels: tdd

#896 devops: #894 Анализ проекта на открытом сонаре
  .github/workflows/qa.yml
  sonar-project.properties
Labels: tech.debt

#892 Расширение инструмента "Управление дымовыми тестами"
  tools/epf/utils/УправлениеДымовымиТестами/УправлениеДымовымиТестами/Forms/Форма/Ext/Form.xml
  tools/epf/utils/УправлениеДымовымиТестами/УправлениеДымовымиТестами/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke

#901 Откат изменений по тесту ПроверкаРеквизитовДокументовКомментарийОтветственный
  tests/smoke/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Тесты_ПроверкаРеквизитовДокументовКомментарийОтветственный/Forms/Форма/Ext/Form/Module.bsl
Labels: smoke

#899 добавить описание новых дымовых тестов
  tests/smoke/readme.md
  tests/smoke/smoke_tests_for_v8std.md
  tools/JSON/providerConfiguration.json
Labels: docs, smoke

#905 Bug/issue 904
  epf/bddRunner/bddRunner/Forms/МодульАсинк/Ext/Form/Module.bsl
  epf/bddRunner/bddRunner/Forms/УправляемаяФорма/Ext/Form/Module.bsl
  epf/xddTestRunner/xddTestRunner/Forms/МодульАсинк/Ext/Form/Module.bsl
Labels: behavior
